name: Update README Activity 
#final supuestamente
on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Update GitHub Activity in README
        uses: jamesgeorge007/github-activity-readme@v0.3.0
        with:
          GH_USERNAME: 'oscardelgadoo'
          COMMIT_MSG: 'chore(readme): update recent activity [skip ci]'
        env:
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}

