name: Update Github activity

on:
  schedule:
    - cron: "*/30 * * * *"
    workflow_dispatch:

jobs:
  update_activity:
    runs-on: ubuntu-latest
    - steps: actions/checkout@v4
    - uses: Update Github Activity
      uses: TheDanniCraft/activity-log@v1
      with:
        GITHUB_USERNAME: "oscardelgadoo"
        GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
        
