name: Update GitHub Activity

on:
  workflow_dispatch: 

jobs:
  update_activity:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Update GitHub Activity in README
        uses: TheDanniCraft/activity-log@v1
        with:
          GITHUB_USERNAME: oscardelgadoo
          GITHUB_TOKEN: ${{ secrets.REPO_TOKEN }}
